//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PolicyValidator.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "12.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Nextlabs\\Root")]
        public string RootDir {
            get {
                return ((string)(this["RootDir"]));
            }
            set {
                this["RootDir"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("portal")]
        public string Enovia_Resource_Type {
            get {
                return ((string)(this["Enovia_Resource_Type"]));
            }
            set {
                this["Enovia_Resource_Type"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("fso")]
        public string Server_Resource_Type {
            get {
                return ((string)(this["Server_Resource_Type"]));
            }
            set {
                this["Server_Resource_Type"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("object")]
        public string SAP_Resource_Type {
            get {
                return ((string)(this["SAP_Resource_Type"]));
            }
            set {
                this["SAP_Resource_Type"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("portal")]
        public string Portal_Resource_Type {
            get {
                return ((string)(this["Portal_Resource_Type"]));
            }
            set {
                this["Portal_Resource_Type"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("fso")]
        public string Filesystem_Resource_Type {
            get {
                return ((string)(this["Filesystem_Resource_Type"]));
            }
            set {
                this["Filesystem_Resource_Type"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool JavaPC {
            get {
                return ((bool)(this["JavaPC"]));
            }
            set {
                this["JavaPC"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("10")]
        public float Timeout_S {
            get {
                return ((float)(this["Timeout_S"]));
            }
            set {
                this["Timeout_S"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("9233")]
        public int PC_Port {
            get {
                return ((int)(this["PC_Port"]));
            }
            set {
                this["PC_Port"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("10.23.58.131")]
        public string PC_IP_Address {
            get {
                return ((string)(this["PC_IP_Address"]));
            }
            set {
                this["PC_IP_Address"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("OPEN,CHECKOUT,CHECKIN,REMOVEFILE,CONNECT,DISCONNECT")]
        public string Enovia_Action_Attributes {
            get {
                return ((string)(this["Enovia_Action_Attributes"]));
            }
            set {
                this["Enovia_Action_Attributes"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("ENOVIA-TYPE,ENOVIA-NAME,IP-ADDRESS")]
        public string Enovia_Resource_Attributes {
            get {
                return ((string)(this["Enovia_Resource_Attributes"]));
            }
            set {
                this["Enovia_Resource_Attributes"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string Enovia_Subject_Attributes {
            get {
                return ((string)(this["Enovia_Subject_Attributes"]));
            }
            set {
                this["Enovia_Subject_Attributes"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string Server_Action_Attributes {
            get {
                return ((string)(this["Server_Action_Attributes"]));
            }
            set {
                this["Server_Action_Attributes"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string Server_Resource_Attributes {
            get {
                return ((string)(this["Server_Resource_Attributes"]));
            }
            set {
                this["Server_Resource_Attributes"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string Server_Subject_Attributes {
            get {
                return ((string)(this["Server_Subject_Attributes"]));
            }
            set {
                this["Server_Subject_Attributes"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("RUN,DELETE,SAP_COPY_FROM")]
        public string Sap_Action_Attributes {
            get {
                return ((string)(this["Sap_Action_Attributes"]));
            }
            set {
                this["Sap_Action_Attributes"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("EXPSECRTY,EXPORTLIC,CMPSECRTY,ECCN,USML,IP_SECRTY")]
        public string Sap_Resource_Attributes {
            get {
                return ((string)(this["Sap_Resource_Attributes"]));
            }
            set {
                this["Sap_Resource_Attributes"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string Sap_Subject_Attributes {
            get {
                return ((string)(this["Sap_Subject_Attributes"]));
            }
            set {
                this["Sap_Subject_Attributes"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("OPEN,RUN,COPY,MOVE,RENAME,DELETE,EMAIL")]
        public string Filesystem_Action_Attributes {
            get {
                return ((string)(this["Filesystem_Action_Attributes"]));
            }
            set {
                this["Filesystem_Action_Attributes"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string Filesystem_Resource_Attributes {
            get {
                return ((string)(this["Filesystem_Resource_Attributes"]));
            }
            set {
                this["Filesystem_Resource_Attributes"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string Filesystem_Subject_Attributes {
            get {
                return ((string)(this["Filesystem_Subject_Attributes"]));
            }
            set {
                this["Filesystem_Subject_Attributes"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("UPLOAD,DOWNLOAD")]
        public string Portal_Action_Attributes {
            get {
                return ((string)(this["Portal_Action_Attributes"]));
            }
            set {
                this["Portal_Action_Attributes"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string Portal_Resource_Attributes {
            get {
                return ((string)(this["Portal_Resource_Attributes"]));
            }
            set {
                this["Portal_Resource_Attributes"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string Portal_Subject_Attributes {
            get {
                return ((string)(this["Portal_Subject_Attributes"]));
            }
            set {
                this["Portal_Subject_Attributes"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("5")]
        public int Connection_Check_Timeout_S {
            get {
                return ((int)(this["Connection_Check_Timeout_S"]));
            }
            set {
                this["Connection_Check_Timeout_S"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("VM-MINH-PC")]
        public string Database_Host {
            get {
                return ((string)(this["Database_Host"]));
            }
            set {
                this["Database_Host"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("270171")]
        public string Database_Port {
            get {
                return ((string)(this["Database_Port"]));
            }
            set {
                this["Database_Port"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("PolicyValidator")]
        public string Database_Collection {
            get {
                return ((string)(this["Database_Collection"]));
            }
            set {
                this["Database_Collection"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("pvadmin")]
        public string Database_User {
            get {
                return ((string)(this["Database_User"]));
            }
            set {
                this["Database_User"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Nextlabs123")]
        public string Database_Password {
            get {
                return ((string)(this["Database_Password"]));
            }
            set {
                this["Database_Password"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("PolicyValidator")]
        public string Database_Name {
            get {
                return ((string)(this["Database_Name"]));
            }
            set {
                this["Database_Name"] = value;
            }
        }
    }
}
